"""Alembic environment configuration — async PostgreSQL.

This file is auto-generated by `alembic init` and customized for FNAI:
- Uses async SQLAlchemy engine (asyncpg)
- Reads DATABASE_URL from app settings (same .env as the app)
- Imports all models so Alembic autogenerate can detect schema changes
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Import app settings so DATABASE_URL is available
from app.core.config import settings

# Import Base + all models so metadata is fully populated for autogenerate
from app.db.base import Base  # noqa: F401
import app.models  # noqa: F401 — registers all models on Base.metadata

# Alembic Config object
config = context.config

# Set sqlalchemy.url from app settings (avoids leaking secrets into alembic.ini)
config.set_main_option("sqlalchemy.url", settings.database_url)

# Logging (uses alembic.ini [loggers] section)
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Target metadata for autogenerate
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Generates SQL scripts without connecting to the database.
    Useful for generating migration SQL to review or apply manually.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Use the naming convention from Base.metadata for constraint names
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Run migrations with an active connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Use the naming convention from Base.metadata
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in async mode (main entry point for async engine)."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connected to database)."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
