"""add_phase2_fields_article_publishlog_prompttemplate

Revision ID: 20b206af0b94
Revises: ba5dbb76fc0b
Create Date: 2026-07-10 06:36:20.371378+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20b206af0b94"
down_revision: Union[str, None] = "ba5dbb76fc0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column(
            "source_document_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="选定的知识库文件 ID 列表; null/空=用整个 KB",
        ),
    )
    op.add_column(
        "articles",
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="定时发布时间; null=不定时",
        ),
    )
    op.add_column(
        "articles",
        sa.Column(
            "is_published",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="是否已通过定时任务发布",
        ),
    )
    op.create_index(
        "ix_articles_scheduled",
        "articles",
        ["scheduled_at"],
        unique=False,
        postgresql_where="scheduled_at IS NOT NULL AND is_published = FALSE",
    )
    op.add_column(
        "prompt_templates",
        sa.Column(
            "table_section_prompt",
            sa.Text(),
            nullable=False,
            server_default="",
            comment="表格类型小节的 prompt（结构化输出）",
        ),
    )
    op.add_column(
        "prompt_templates",
        sa.Column(
            "list_section_prompt",
            sa.Text(),
            nullable=False,
            server_default="",
            comment="列表类型小节的 prompt（结构化输出）",
        ),
    )
    op.add_column(
        "publish_logs",
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="发布效果统计: 阅读量/点赞数等",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publish_logs", "metrics")
    op.drop_column("prompt_templates", "list_section_prompt")
    op.drop_column("prompt_templates", "table_section_prompt")
    op.drop_index(
        "ix_articles_scheduled",
        table_name="articles",
        postgresql_where="scheduled_at IS NOT NULL AND is_published = FALSE",
    )
    op.drop_column("articles", "is_published")
    op.drop_column("articles", "scheduled_at")
    op.drop_column("articles", "source_document_ids")
    # ### end Alembic commands ###
